#!/usr/bin/env python3
"""zedcfg - build, install and audit the zed-initiative Zed configuration.

Standard library only (Python 3.9+), one file, no network access.

  build      core/ + enabled packs/ + local.jsonc  ->  dist/
  install    build, then copy dist/ into Zed's config dir(s):
               Linux/macOS  ~/.config/zed
               WSL          ~/.config/zed  AND  the Windows side (%APPDATA%\\Zed)
               Windows      %APPDATA%\\Zed
  doctor     check the tools the enabled packs need, print install commands
             (it never installs anything itself)
  audit      security summary: AI settings, worktree trust, extensions,
             extension capability grants, binaries and task commands
  list       show available packs and whether they are enabled
  new-pack   scaffold packs/<name> from packs/_template
"""
from __future__ import annotations

import argparse
import copy
import datetime as _dt
import difflib
import hashlib
import json
import os
import platform
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import NoReturn

REPO = Path(__file__).resolve().parent
CORE = REPO / "core"
PACKS = REPO / "packs"
DIST = REPO / "dist"
CONFIG = REPO / "config.jsonc"
LOCAL = REPO / "local.jsonc"

MANAGED_FILES = ("settings.json", "keymap.json", "tasks.json")
STATE_FILE = "zed-initiative.state.json"
BACKUP_DIR = "zed-initiative-backups"
PACK_KEYS = {"description", "requires", "settings", "keymap", "tasks"}
REQUIRE_KEYS = {"bin", "why", "optional", "install", "zed_dir"}
# Settings Zed rewrites in settings.json by itself (theme picker, font zoom,
# `workspace: toggle vim mode`, dragging a panel to another dock). Their
# installed values survive reinstalls. Dotted = nested key.
UI_KEYS = (
    "vim_mode", "theme", "icon_theme", "ui_font_size", "buffer_font_size",
    "project_panel.dock", "outline_panel.dock", "git_panel.dock", "terminal.dock", "debugger.dock",
)


def _get_path(obj: dict, dotted: str):
    for part in dotted.split("."):
        if not isinstance(obj, dict) or part not in obj:
            return KeyError
        obj = obj[part]
    return obj


def _set_path(obj: dict, dotted: str, value) -> None:
    *parents, last = dotted.split(".")
    for part in parents:
        obj = obj.setdefault(part, {})
    obj[last] = value


def is_ui_key(path: str) -> bool:
    return any(path == k or path.startswith(k + ".") for k in UI_KEYS)
# Only lowercase ${names} are ours; Zed's own task/snippet variables are
# uppercase ($ZED_FILE, ${ZED_WORKTREE_ROOT}) or numeric (${1:default}).
VAR_RE = re.compile(r"\$\{([a-z][a-z0-9_]*)\}")

HEADER = (
    "// GENERATED by zed-initiative/zedcfg.py - edits here are overwritten on the next install,\n"
    "// except the UI-managed keys ({ui}).\n"
    "// Source of truth: {repo} (core/, packs/, config.jsonc, local.jsonc)\n"
)


# --------------------------------------------------------------------------- output

_COLOR = sys.stdout.isatty() and not os.environ.get("NO_COLOR")


def _c(code: str, text: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _COLOR else text


def ok(msg: str) -> None:
    print(f"  {_c('32', 'ok')}  {msg}")


def warn(msg: str) -> None:
    print(f"  {_c('33', '!!')}  {msg}")


def bad(msg: str) -> None:
    print(f"  {_c('31', 'xx')}  {msg}")


def heading(msg: str) -> None:
    print(f"\n{_c('1', msg)}")


def die(msg: str) -> NoReturn:
    print(f"error: {msg}", file=sys.stderr)
    raise SystemExit(2)


# --------------------------------------------------------------------------- JSONC

def _scan_string(text: str, i: int) -> int:
    """Return the index just past the JSON string starting at text[i] == '"'."""
    j = i + 1
    n = len(text)
    while j < n and text[j] != '"':
        j += 2 if text[j] == "\\" else 1
    return j + 1


def strip_jsonc(text: str) -> str:
    """Turn JSONC into JSON: drop // and /* */ comments and trailing commas.

    Strings are left untouched and newlines inside block comments are kept, so
    json error line numbers still point at the right line of the source file.
    """
    out = []
    i, n = 0, len(text)
    while i < n:
        c = text[i]
        if c == '"':
            j = _scan_string(text, i)
            out.append(text[i:j])
            i = j
        elif text.startswith("//", i):
            j = text.find("\n", i)
            i = n if j == -1 else j
        elif text.startswith("/*", i):
            j = text.find("*/", i + 2)
            if j == -1:
                raise ValueError("unterminated /* comment")
            out.append("\n" * text.count("\n", i, j))
            i = j + 2
        else:
            out.append(c)
            i += 1
    text = "".join(out)

    out = []
    i, n = 0, len(text)
    while i < n:
        c = text[i]
        if c == '"':
            j = _scan_string(text, i)
            out.append(text[i:j])
            i = j
            continue
        if c == ",":
            j = i + 1
            while j < n and text[j] in " \t\r\n":
                j += 1
            if j < n and text[j] in "}]":
                i += 1
                continue
        out.append(c)
        i += 1
    return "".join(out)


def parse_jsonc(text: str, source: str = "<string>"):
    try:
        return json.loads(strip_jsonc(text))
    except ValueError as e:
        raise ValueError(f"{source}: {e}") from None


def load_jsonc(path: Path):
    try:
        return parse_jsonc(Path(path).read_text(encoding="utf-8"), str(path))
    except OSError as e:
        die(f"cannot read {path}: {e}")
    except ValueError as e:
        die(str(e))


# --------------------------------------------------------------------------- merge

REPLACE = "$replace"


def _is_replace(value) -> bool:
    return isinstance(value, dict) and set(value) == {REPLACE}


def unwrap(value):
    """Strip {"$replace": x} markers, recursively."""
    if _is_replace(value):
        return unwrap(value[REPLACE])
    if isinstance(value, dict):
        return {k: unwrap(v) for k, v in value.items()}
    if isinstance(value, list):
        return [unwrap(v) for v in value]
    return value


class Merger:
    """Deep merge with provenance.

    Objects merge recursively, arrays concatenate (dropping exact duplicates),
    scalars are replaced. {"$replace": value} replaces instead of merging.
    When one pack replaces a scalar another pack set, a warning is recorded;
    core defaults and local.jsonc overrides are silent.
    """

    def __init__(self) -> None:
        self.owner: dict[tuple, str] = {}
        self.warnings: list[str] = []

    def merge(self, base: dict, over: dict, source: str, path: tuple = ()) -> dict:
        for key, value in over.items():
            p = path + (key,)
            cur = base.get(key)
            if _is_replace(value):
                base[key] = unwrap(value)
                self._claim(base[key], source, p)
            elif isinstance(cur, dict) and isinstance(value, dict):
                self.merge(cur, value, source, p)
            elif isinstance(cur, list) and isinstance(value, list):
                for item in unwrap(value):
                    if item not in cur:
                        cur.append(item)
            else:
                value = unwrap(value)
                prev = self.owner.get(p)
                if (
                    key in base
                    and cur != value
                    and prev not in (None, "core", source)
                    and source != "local"
                ):
                    self.warnings.append(
                        f"{'.'.join(p)}: pack '{source}' overrides pack '{prev}' ({cur!r} -> {value!r})"
                    )
                base[key] = value
                self._claim(value, source, p)
        return base

    def _claim(self, value, source: str, p: tuple) -> None:
        self.owner[p] = source
        if isinstance(value, dict):
            for k, v in value.items():
                self._claim(v, source, p + (k,))


def substitute(obj, variables: dict, where: str = "", _stack: tuple = ()):
    """Replace ${var} placeholders.

    A string that is exactly "${var}" takes the variable's value as-is (so a
    list var stays a list); inside a list such a list value is spliced in.
    Variable values may themselves use other variables.
    """

    def lookup(name: str):
        if name not in variables:
            die(f"{where}: unknown variable ${{{name}}} (define it under \"vars\" in config.jsonc)")
        if name in _stack:
            die(f"{where}: variable cycle: {' -> '.join(_stack + (name,))}")
        return substitute(variables[name], variables, where, _stack + (name,))

    def as_text(name: str) -> str:
        value = lookup(name)
        if isinstance(value, (dict, list)):
            die(f"{where}: ${{{name}}} is a {type(value).__name__}; it can only stand alone, not inside a string")
        return str(value)

    if isinstance(obj, str):
        m = VAR_RE.fullmatch(obj)
        if m:
            return lookup(m.group(1))
        return VAR_RE.sub(lambda m: as_text(m.group(1)), obj)
    if isinstance(obj, list):
        out = []
        for item in obj:
            m = VAR_RE.fullmatch(item) if isinstance(item, str) else None
            value = lookup(m.group(1)) if m else substitute(item, variables, where, _stack)
            if m and isinstance(value, list):
                out.extend(value)
            else:
                out.append(value)
        return out
    if isinstance(obj, dict):
        return {
            (VAR_RE.sub(lambda m: as_text(m.group(1)), k)): substitute(v, variables, where, _stack)
            for k, v in obj.items()
        }
    return obj


# --------------------------------------------------------------------------- platform

def is_windows() -> bool:
    return os.name == "nt"


def is_wsl() -> bool:
    return bool(os.environ.get("WSL_DISTRO_NAME")) or "microsoft" in platform.release().lower()


def xdg(var: str, fallback: str) -> Path:
    value = os.environ.get(var)
    return Path(value) if value else Path.home() / fallback


def data_home() -> Path:
    """Where helper scripts keep data (e.g. extracted CRD schemas). Never inside the repo."""
    if is_windows():
        return Path(os.environ.get("LOCALAPPDATA", Path.home())) / "zed-initiative"
    return xdg("XDG_DATA_HOME", ".local/share") / "zed-initiative"


def zed_data_dir() -> Path:
    if is_windows():
        return Path(os.environ.get("LOCALAPPDATA", Path.home())) / "Zed"
    if sys.platform == "darwin":
        return Path.home() / "Library/Application Support/Zed"
    return xdg("XDG_DATA_HOME", ".local/share") / "zed"


def windows_appdata_from_wsl() -> Path | None:
    """Resolve the Windows user's %APPDATA% as a /mnt/... path from inside WSL."""
    try:
        win = subprocess.run(
            ["cmd.exe", "/c", "echo %APPDATA%"], cwd="/mnt/c", capture_output=True, text=True, timeout=15
        ).stdout.strip()
        if not win or "%" in win:
            return None
        return Path(subprocess.run(["wslpath", "-u", win], capture_output=True, text=True, timeout=15).stdout.strip())
    except (OSError, subprocess.SubprocessError):
        return None


def default_targets(include_windows: bool = True) -> list[Path]:
    if is_windows():
        return [Path(os.environ["APPDATA"]) / "Zed"]
    targets = [xdg("XDG_CONFIG_HOME", ".config") / "zed"]
    if is_wsl() and include_windows:
        appdata = windows_appdata_from_wsl()
        if appdata:
            targets.append(appdata / "Zed")
        else:
            warn("WSL detected but the Windows %APPDATA% could not be resolved; use --target-dir for the Windows side")
    return targets


def builtin_vars() -> dict:
    return {
        "repo": REPO.as_posix(),
        "home": Path.home().as_posix(),
        "python": "python" if is_windows() else "python3",
        "data_dir": data_home().as_posix(),
    }


# --------------------------------------------------------------------------- build

class Build:
    def __init__(self) -> None:
        self.settings: dict = {}
        self.keymap: list = []
        self.tasks: list = []
        self.snippets: dict[str, dict] = {}
        self.packs: list[dict] = []
        self.core_settings: dict = {}
        self.warnings: list[str] = []
        self.variables: dict = {}

    def files(self) -> dict[str, str]:
        header = HEADER.format(ui=", ".join(UI_KEYS), repo=REPO.as_posix())
        out = {
            "settings.json": header + dump(self.settings),
            "keymap.json": header + dump(self.keymap),
            "tasks.json": header + dump(self.tasks),
        }
        for name, snippets in sorted(self.snippets.items()):
            out[f"snippets/{name}"] = dump(snippets)
        return out


def dump(obj) -> str:
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


def available_packs() -> list[str]:
    return sorted(p.name for p in PACKS.iterdir() if (p / "pack.jsonc").is_file() and not p.name.startswith("_"))


def load_config() -> tuple[list[str], dict, dict]:
    cfg = load_jsonc(CONFIG)
    local = load_jsonc(LOCAL) if LOCAL.exists() else {}
    packs = list(cfg.get("packs", []))
    for name in local.get("enable", []):
        if name not in packs:
            packs.append(name)
    disabled = set(local.get("disable", []))
    packs = [p for p in packs if p not in disabled]
    variables = builtin_vars()
    variables.update(cfg.get("vars", {}))
    variables.update(local.get("vars", {}))
    return packs, variables, local


def load_pack(name: str) -> dict:
    path = PACKS / name / "pack.jsonc"
    if not path.is_file():
        die(f"pack '{name}' not found (expected {path}); available: {', '.join(available_packs())}")
    pack = load_jsonc(path)
    if not isinstance(pack, dict):
        die(f"{path}: must be a JSON object")
    unknown = set(pack) - PACK_KEYS
    if unknown:
        die(f"{path}: unknown keys {sorted(unknown)}; allowed: {sorted(PACK_KEYS)}")
    for req in pack.get("requires", []):
        unknown = set(req) - REQUIRE_KEYS
        if unknown or not req.get("bin"):
            die(f"{path}: bad \"requires\" entry {req}; keys allowed: {sorted(REQUIRE_KEYS)}")
    pack["name"] = name
    return pack


def merge_snippets(into: dict, directory: Path, source: str, warnings: list) -> None:
    if not directory.is_dir():
        return
    for f in sorted(directory.glob("*.json")):
        data = load_jsonc(f)
        bucket = into.setdefault(f.name, {})
        for key, snippet in data.items():
            if key in bucket and bucket[key] != snippet:
                warnings.append(f"snippets/{f.name}: '{key}' from '{source}' replaces an earlier definition")
            bucket[key] = snippet


def build() -> Build:
    packs, variables, local = load_config()
    b = Build()
    b.variables = variables
    m = Merger()

    b.core_settings = load_jsonc(CORE / "settings.jsonc")
    m.merge(b.settings, b.core_settings, "core")
    b.keymap = list(load_jsonc(CORE / "keymap.jsonc"))
    b.tasks = list(load_jsonc(CORE / "tasks.jsonc"))
    merge_snippets(b.snippets, CORE / "snippets", "core", m.warnings)

    for name in packs:
        pack = load_pack(name)
        b.packs.append(pack)
        m.merge(b.settings, pack.get("settings", {}), name)
        b.keymap += pack.get("keymap", [])
        b.tasks += pack.get("tasks", [])
        merge_snippets(b.snippets, PACKS / name / "snippets", name, m.warnings)

    m.merge(b.settings, local.get("settings", {}), "local")
    b.keymap += local.get("keymap", [])
    b.tasks += local.get("tasks", [])

    b.settings = substitute(b.settings, variables, "settings")
    b.keymap = substitute(b.keymap, variables, "keymap")
    b.tasks = substitute(b.tasks, variables, "tasks")
    for pack in b.packs:
        pack["requires"] = substitute(pack.get("requires", []), variables, f"packs/{pack['name']}")

    labels = [t.get("label") for t in b.tasks]
    for label in sorted({x for x in labels if labels.count(x) > 1}):
        m.warnings.append(f"tasks: duplicate label '{label}'")
    b.warnings = m.warnings
    return b


def write_dist(b: Build) -> None:
    if (DIST / "snippets").is_dir():
        shutil.rmtree(DIST / "snippets")
    for rel, text in b.files().items():
        path = DIST / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")


def cmd_build(args) -> int:
    b = build()
    write_dist(b)
    for w in b.warnings:
        warn(w)
    print(f"built {len(b.files())} files into {DIST} from core + {len(b.packs)} packs: "
          f"{', '.join(p['name'] for p in b.packs)}")
    return 0


# --------------------------------------------------------------------------- install

def sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def changed_paths(old, new, path: str = "") -> list[str]:
    """Dotted paths whose values differ between two JSON values."""
    if isinstance(old, dict) and isinstance(new, dict):
        out = []
        for k in sorted(set(old) | set(new)):
            p = f"{path}.{k}" if path else k
            if k not in old or k not in new:
                out.append(p)
            else:
                out += changed_paths(old[k], new[k], p)
        return out
    return [] if old == new else [path or "<root>"]


def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".zed-initiative.tmp")
    tmp.write_text(text, encoding="utf-8")
    os.replace(tmp, path)


def unified(old: str, new: str, name: str) -> str:
    return "".join(difflib.unified_diff(
        old.splitlines(keepends=True), new.splitlines(keepends=True), f"installed/{name}", f"new/{name}"
    ))


def plan_target(target: Path, b: Build, reset_ui: bool) -> tuple[list, list[str], list[str]]:
    """Work out what installing into `target` would do.

    Returns (actions, drift, notes). Each action is (rel, kind, new_text,
    old_text) with kind one of create/update/unchanged/remove. `drift` lists
    edits made outside the repo (install refuses without --force); `notes` are
    informational (e.g. a pre-existing file that will be backed up).
    """
    state_path = target / STATE_FILE
    state = {}
    if state_path.is_file():
        try:
            state = json.loads(state_path.read_text(encoding="utf-8"))
        except ValueError:
            state = {}
    recorded = state.get("files", {})
    files = b.files()
    actions, drift, notes = [], [], []

    for rel, new_text in files.items():
        path = target / rel
        old_text = path.read_text(encoding="utf-8") if path.is_file() else None

        if rel == "settings.json" and old_text is not None and not reset_ui:
            try:
                installed = parse_jsonc(old_text, str(path))
            except ValueError:
                installed = None
            if isinstance(installed, dict):
                keep = {k: v for k in UI_KEYS if (v := _get_path(installed, k)) is not KeyError}
                if keep:
                    settings = copy.deepcopy(b.settings)
                    for k, v in keep.items():
                        _set_path(settings, k, v)
                    new_text = HEADER.format(ui=", ".join(UI_KEYS), repo=REPO.as_posix()) + dump(settings)

        if old_text is None:
            actions.append((rel, "create", new_text, None))
            continue
        if rel not in recorded:
            notes.append(f"{rel} exists and was not written by zed-initiative; it will be backed up first")
        elif sha256(old_text) != recorded[rel]:
            if rel == "settings.json" and "settings" in state:
                try:
                    now = parse_jsonc(old_text, rel)
                    touched = [p for p in changed_paths(state["settings"], now) if not is_ui_key(p)]
                    if touched:
                        drift.append(f"{rel}: edited outside zed-initiative at: {', '.join(touched[:8])}"
                                     + (" ..." if len(touched) > 8 else ""))
                except ValueError:
                    drift.append(f"{rel}: no longer valid JSONC")
            else:
                drift.append(f"{rel}: edited outside zed-initiative")
        kind = "unchanged" if old_text == new_text else "update"
        actions.append((rel, kind, new_text, old_text))

    for rel in recorded:
        if rel not in files and (target / rel).is_file():
            old_text = (target / rel).read_text(encoding="utf-8")
            if sha256(old_text) != recorded[rel]:
                drift.append(f"{rel}: no longer generated but edited outside zed-initiative")
            actions.append((rel, "remove", None, old_text))
    return actions, drift, notes


def cmd_install(args) -> int:
    b = build()
    write_dist(b)
    for w in b.warnings:
        warn(w)
    targets = [Path(t).expanduser() for t in args.target_dir] if args.target_dir else default_targets(not args.no_windows)
    stamp = _dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    exit_code = 0

    for target in targets:
        heading(f"target: {target}")
        actions, drift, notes = plan_target(target, b, args.reset_ui)
        for n in notes:
            warn(n)
        if drift and not args.force:
            for d in drift:
                bad(d)
            print("     Move those edits into local.jsonc (or a pack), or re-run with --force"
                  " (the current files are backed up first).")
            if args.dry_run:
                for rel, kind, new_text, old_text in actions:
                    if kind == "update":
                        print(unified(old_text, new_text, rel))
            exit_code = 1
            continue

        for rel, kind, new_text, old_text in actions:
            if kind == "unchanged":
                ok(f"{rel} unchanged")
                continue
            if args.dry_run:
                print(f"  --  would {kind} {rel}")
                if kind == "update":
                    print(unified(old_text, new_text, rel))
                continue
            if old_text is not None:
                backup = target / BACKUP_DIR / stamp / rel
                backup.parent.mkdir(parents=True, exist_ok=True)
                backup.write_text(old_text, encoding="utf-8")
            if kind == "remove":
                (target / rel).unlink()
                ok(f"removed {rel} (no longer generated; backup kept)")
            else:
                atomic_write(target / rel, new_text)
                ok(f"{kind}d {rel}" if kind == "update" else f"created {rel}")

        if args.dry_run:
            continue
        written = {rel: sha256(new_text) for rel, kind, new_text, _ in actions if kind != "remove"}
        settings_text = next(t for r, _, t, _ in actions if r == "settings.json")
        state = {
            "about": "Written by zed-initiative/zedcfg.py to detect edits made outside the repo. Safe to delete.",
            "repo": REPO.as_posix(),
            "installed_at": _dt.datetime.now().isoformat(timespec="seconds"),
            "packs": [p["name"] for p in b.packs],
            "files": written,
            "settings": parse_jsonc(settings_text),
        }
        atomic_write(target / STATE_FILE, dump(state))
        if (target / BACKUP_DIR / stamp).is_dir():
            ok(f"previous files backed up to {target / BACKUP_DIR / stamp}")

    if not args.dry_run and exit_code == 0:
        print("\nZed reloads settings, keymap, tasks and snippets automatically.")
    return exit_code


# --------------------------------------------------------------------------- doctor

PKG_MANAGERS = ("pacman", "apt", "dnf", "zypper", "brew", "winget", "scoop")
PKG_INSTALL = {
    "pacman": "sudo pacman -S --needed {}",
    "apt": "sudo apt install {}",
    "dnf": "sudo dnf install {}",
    "zypper": "sudo zypper install {}",
    "brew": "brew install {}",
    "winget": "winget install -e --id {}",
    "scoop": "scoop install {}",
    # No root, no lifecycle scripts; binaries land in ~/.local/bin.
    "npm": "npm install --global --prefix ~/.local --ignore-scripts {}",
    "pipx": "pipx install {}",
    "manual": "{}",
}


def detect_pkg_manager() -> str | None:
    for pm in PKG_MANAGERS:
        exe = "apt-get" if pm == "apt" else pm
        if shutil.which(exe):
            return pm
    return None


def zed_log_servers(log: Path) -> tuple[dict[str, str], str]:
    """Map language server -> binary, for Zed's most recent run only.

    Returns ({server: binary}, when) so that servers started in older sessions
    (possibly before the system packages existed) aren't reported as current.
    """
    servers: dict[str, str] = {}
    if not log.is_file():
        return servers, ""
    lines = log.read_text(encoding="utf-8", errors="replace").splitlines()
    starts = [i for i, line in enumerate(lines) if "========== starting zed version" in line]
    session = lines[starts[-1]:] if starts else lines
    when = session[0].split(" ", 1)[0] if session else ""
    found = re.compile(r"found user-installed language server for ([\w.-]+)\. path: \"([^\"]+)\"")
    started = re.compile(r"starting language server process\. binary path: \"([^\"]+)\".*?args: \[(.*)\]")
    for line in session:
        if m := found.search(line):
            servers[m.group(1)] = m.group(2)
        elif m := started.search(line):
            binary, argv = m.group(1), m.group(2)
            script = re.search(r"\"([^\"]*(?:languages|extensions)[/\\][^\"]+)\"", argv)
            where = script.group(1) if script else binary
            name = re.search(r"[/\\](?:languages|work)[/\\]([^/\\]+)", where)
            key = name.group(1) if name else Path(binary).name
            if where not in servers.values():  # already reported under its LSP name
                servers.setdefault(key, where)
    return servers, when


def cmd_doctor(args) -> int:
    b = build()
    pm = detect_pkg_manager()
    missing: dict[str, list[str]] = {}
    problems = 0

    tools: dict[str, dict] = {}
    for pack in b.packs:
        for req in pack.get("requires", []):
            t = tools.setdefault(req["bin"], {"packs": [], "why": req.get("why", ""), "optional": True, "install": {}})
            t["packs"].append(pack["name"])
            t["optional"] = t["optional"] and bool(req.get("optional"))
            t["install"] = {**req.get("install", {}), **t["install"]}

    heading(f"tools needed by enabled packs (package manager: {pm or 'none found'})")
    for binary, t in tools.items():
        path = shutil.which(binary)
        label = f"{binary:<24} [{', '.join(t['packs'])}]"
        if path:
            ok(f"{label} -> {path}")
            continue
        install = t["install"]
        how = next(((k, install[k]) for k in (pm, "npm", "pipx", "manual") if k and install.get(k)), None)
        if t["optional"]:
            warn(f"{label} optional, missing: {t['why']}")
        else:
            bad(f"{label} missing: {t['why']}")
            problems += 1
        if how:
            missing.setdefault(how[0], []).append(how[1])
    if missing:
        heading("to install the missing tools (review first; nothing is run for you)")
        for manager, pkgs in missing.items():
            if manager in ("manual",):
                for p in pkgs:
                    print(f"  {p}")
            elif manager == "winget":
                for p in pkgs:
                    print(f"  {PKG_INSTALL[manager].format(p)}")
            else:
                print(f"  {PKG_INSTALL[manager].format(' '.join(dict.fromkeys(pkgs)))}")

    heading("zed")
    zed = shutil.which("zed") or shutil.which("zeditor")
    if zed:
        try:
            version = subprocess.run([zed, "--version"], capture_output=True, text=True, timeout=20).stdout.strip()
        except (OSError, subprocess.SubprocessError):
            version = "?"
        ok(f"{zed}: {version}")
    else:
        warn("zed CLI not on PATH (fine on the WSL side of a Windows setup)")

    data = zed_data_dir()
    downloads = data / "languages"
    downloaded = sorted(p for p in downloads.glob("*") if p.is_dir()) if downloads.is_dir() else []
    # A download is superseded when the pack's binary for it now resolves on PATH.
    supersedes = {req["zed_dir"]: req["bin"] for pack in b.packs for req in pack.get("requires", []) if req.get("zed_dir")}
    disabled = {"package-version-server"} if any(
        "!package-version-server" in (lang.get("language_servers") or [])
        for lang in b.settings.get("languages", {}).values()) else set()
    stale = [p for p in downloaded if (p.name in supersedes and shutil.which(supersedes[p.name])) or p.name in disabled]
    if downloaded:
        warn(f"language servers Zed downloaded into {downloads} (it does that when it finds none on PATH):")
        for p in downloaded:
            print(f"       {p.name}{'   <- superseded, safe to remove' if p in stale else ''}")
        if stale and not args.clean_downloads:
            print("       Remove the superseded ones with: python3 zedcfg.py doctor --clean-downloads")
        for p in stale if args.clean_downloads else []:
            shutil.rmtree(p)
            ok(f"removed {p}")
    else:
        ok(f"no Zed-downloaded language servers in {downloads}")

    servers, when = zed_log_servers(data / "logs" / "Zed.log")
    if servers:
        heading(f"language servers Zed actually started in its last run ({when})")
        for name, where in sorted(servers.items()):
            if where.startswith(str(data / "languages")):
                warn(f"{name:<24} {where}  <- Zed's own download, not your PATH install")
            elif where.startswith(str(data / "extensions")):
                ok(f"{name:<24} {where}  (extension-managed, allowed by its grant)")
            else:
                ok(f"{name:<24} {where}")

    declared = {k for k, v in b.settings.get("auto_install_extensions", {}).items() if v}
    installed_dir = data / "extensions" / "installed"
    installed = {p.name for p in installed_dir.iterdir()} if installed_dir.is_dir() else set()
    heading("extensions")
    for name in sorted(declared):
        (ok if name in installed else warn)(f"{name:<28} {'installed' if name in installed else 'declared, installs on next Zed start'}")
    for name in sorted(installed - declared):
        warn(f"{name:<28} installed but not declared by any pack; remove it via `zed: extensions` if unused")

    for w in b.warnings:
        warn(w)
    return 1 if problems else 0


# --------------------------------------------------------------------------- audit

def cmd_audit(args) -> int:
    b = build()
    s = b.settings
    agent = s.get("agent", {})
    ep = s.get("edit_predictions", {})

    heading("AI")
    (ok if s.get("disable_ai") else bad)(f"disable_ai: {s.get('disable_ai')}  (Zed's master switch for every AI feature)")
    (ok if agent.get("enabled") is False else bad)(f"agent.enabled: {agent.get('enabled')}, agent.button: {agent.get('button')}")
    (ok if not s.get("context_servers") else bad)(f"context_servers (MCP): {list(s.get('context_servers', {})) or 'none'}")
    (ok if not s.get("agent_servers") else bad)(f"agent_servers (external agents): {list(s.get('agent_servers', {})) or 'none'}")
    ok(f"edit_predictions.provider: {ep.get('provider')}, data collection: {ep.get('allow_data_collection')}")
    for name, profile in s.get("profiles", {}).items():
        ps = profile.get("settings", {})
        print(f"       profile '{name}': disable_ai={ps.get('disable_ai')}, "
              f"agent.enabled={ps.get('agent', {}).get('enabled')}, "
              f"provider={ps.get('edit_predictions', {}).get('provider')}, "
              f"mode={ps.get('edit_predictions', {}).get('mode')}")
    print(f"       never sent to Copilot: {', '.join(ep.get('disabled_globs', []))}")

    heading("trust & telemetry")
    trust = s.get("session", {}).get("trust_all_worktrees")
    (ok if trust is False else bad)(f"session.trust_all_worktrees: {trust}")
    tel = s.get("telemetry", {})
    (ok if not tel.get("metrics") and not tel.get("diagnostics") else warn)(f"telemetry: {tel}")

    heading("extensions (auto_install_extensions) and what they may do")
    grants = s.get("granted_extension_capabilities", [])
    for source, settings in [("core", b.core_settings)] + [(p["name"], p.get("settings", {})) for p in b.packs]:
        exts = [k for k, v in settings.get("auto_install_extensions", {}).items() if v]
        caps = settings.get("granted_extension_capabilities", [])
        if exts or caps:
            print(f"  [{source}] extensions: {', '.join(exts) or '-'}")
            for cap in caps:
                print(f"         grant: {json.dumps(cap)}")
    (ok if all(c.get("command") != "*" and c.get("host") != "*" and c.get("package") != "*" for c in grants) else bad)(
        f"{len(grants)} capability grant(s) total, no wildcards" if grants else "no capability grants: extensions cannot exec, download or npm-install")

    heading("binaries the packs rely on (resolved from PATH)")
    for pack in b.packs:
        bins = [r["bin"] for r in pack.get("requires", [])]
        if bins:
            print(f"  [{pack['name']}] {', '.join(bins)}")

    heading("task commands (run only when you trigger them)")
    for t in b.tasks:
        print(f"  {t.get('label')}:  {t.get('command')} {' '.join(t.get('args', []))}")
    return 0


# --------------------------------------------------------------------------- list / new-pack

def cmd_list(args) -> int:
    packs, _, _ = load_config()
    for name in available_packs():
        desc = load_jsonc(PACKS / name / "pack.jsonc").get("description", "")
        mark = _c("32", "on ") if name in packs else _c("2", "off")
        print(f"  {mark}  {name:<16} {desc}")
    print("\nenable/disable in config.jsonc (\"packs\") or per machine in local.jsonc (\"enable\"/\"disable\").")
    return 0


def cmd_new_pack(args) -> int:
    name = args.name
    if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", name):
        die("pack names are lowercase letters, digits and dashes")
    dest = PACKS / name
    if dest.exists():
        die(f"{dest} already exists")
    shutil.copytree(PACKS / "_template", dest)
    pack = dest / "pack.jsonc"
    pack.write_text(pack.read_text(encoding="utf-8").replace("__NAME__", name), encoding="utf-8")
    print(f"created {dest}\n  1. edit {pack}\n  2. add \"{name}\" to \"packs\" in config.jsonc\n"
          f"  3. python3 zedcfg.py audit && python3 zedcfg.py install")
    return 0


# --------------------------------------------------------------------------- main

def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="zedcfg", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("build", help="render dist/ from core + packs + local.jsonc")
    p = sub.add_parser("install", help="build and install into Zed's config dir(s)")
    p.add_argument("--dry-run", action="store_true", help="show what would change, write nothing")
    p.add_argument("--force", action="store_true", help="overwrite files edited outside the repo (after backing them up)")
    p.add_argument("--reset-ui", action="store_true", help=f"don't keep the installed values of {', '.join(UI_KEYS)}")
    p.add_argument("--no-windows", action="store_true", help="under WSL, skip the Windows-side config")
    p.add_argument("--target-dir", action="append", metavar="DIR", help="install here instead (repeatable)")
    p = sub.add_parser("doctor", help="check tools, downloads and extensions; print install commands")
    p.add_argument("--clean-downloads", action="store_true",
                   help="delete language servers Zed downloaded that a PATH install now supersedes")
    sub.add_parser("audit", help="print the security summary")
    sub.add_parser("list", help="list packs")
    p = sub.add_parser("new-pack", help="scaffold a pack from packs/_template")
    p.add_argument("name")
    args = parser.parse_args(argv)
    return {
        "build": cmd_build, "install": cmd_install, "doctor": cmd_doctor,
        "audit": cmd_audit, "list": cmd_list, "new-pack": cmd_new_pack,
    }[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
